### PR TITLE
Implemented "aemm build" + misc. cleanup & fixes

### PR DESCRIPTION
**Pull request by HenryPing**

### CODE REVIEW

**Comment by adzellman** [comment]
Would it make sense for us to squash these before putting them into the trunk?

**Comment by HenryPing** [comment]
"squash these" - what are you referring to?

**Comment by adzellman** [comment]
Squashing would be to roll the many commits into one. It is a common practice in open source repositories to reduce commit spam.

**Comment by adzellman** [comment]
Also, it seems that HenryPing/master is not up-to-date with adobe-marketing-cloud-mobile, so there are quite a few changes from master included in this PR. Is that intended?

**Comment by adzellman** [comment]
I can handle the squashing if you'd prefer.

**Comment by HenryPing** [comment]
Sounds good, just checked that CustomPlugin branch is up-to-date with Trunk's master, am I missing anything?

**Comment by adzellman** [comment]
There are three branches in play here: HenryPing/CustomPlugin, HenryPing/master, and adobe-marketing-cloud-mobile/master. This PR was made from HenryPing/CustomPlugin -> HenryPing/master.

I will close this one and open a squashed PR from HenryPing/CustomPlugin -> adobe-marketing-cloud-mobile/master

**Pull request closed without merging**
